#!/usr/bin/env bash
# ----------------------------------------------------------------
# Cutefetch Mac v1.0
#
# Tiny colored fetch script with cute little animals
#
# Authored by: elenapan (https://github.com/elenapan)
# Modified by: strafe (https://github.com/strafe)
# Modified by: cybardev (https://github.com/cybardev)
# ----------------------------------------------------------------

# store color codes in variables
function setup_colors() {
    for i in {0..7}; do
        printf -v "c${i}" '%b' "\e[3${i}m"
    done

    readonly d=$'\e[1m'
    readonly t=$'\e[0m'
    readonly v=$'\e[7m'
}

# name of window manager
function get_wm() {
    # From neofetch (https://github.com/dylanaraps/neofetch).
    local -r ps_line="$(ps -e | grep -o \
    -e "[S]pectacle" \
    -e "[A]methyst" \
    -e "[k]wm" \
    -e "[c]hun[k]wm" \
    -e "[y]abai" \
    -e "[R]ectangle")"

    case $ps_line in
        *chunkwm*)   echo chunkwm ;;
        *kwm*)       echo Kwm ;;
        *yabai*)     echo yabai ;;
        *Amethyst*)  echo Amethyst ;;
        *Spectacle*) echo Spectacle ;;
        *Rectangle*) echo Rectangle ;;
        *)           echo Quartz Compositor ;;
    esac
}

# set necessary variables
function setup_variables() {
    readonly wmname="$(get_wm)"
    readonly kernel="$(uname -r | cut -d '-' -f1)"
    readonly shell="$(basename "$SHELL")"
    readonly resolution="$(system_profiler SPDisplaysDataType | grep Retina | awk '/Resolution:/ {printf $2"x"$4""}')"
    readonly netname="$(/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I  | awk -F' SSID: '  '/ SSID: / {print $2}')"
}

# set the eyes, ^.^ by default for cat, . . for bunny
eyes() {
    if [[ -z $1 ]]; then
        echo "^.^"
    elif [[ $1 = "0" ]]; then
        echo ". ."
    elif [[ $1 = "1" ]]; then
        echo "· ·"
    elif [[ $1 = "2" ]]; then
        echo "^ ^"
    elif [[ $1 = "3" ]]; then
        echo "- -"
    elif [[ $1 = "4" ]]; then
        echo "~ ~"
    elif [[ $1 = "5" ]]; then
        echo "* *"
    elif [[ $1 = "6" ]]; then
        echo "^.^"
    elif [[ $1 = "7" ]]; then
        echo "-.-"
    elif [[ $1 = "8" ]]; then
        echo "~.~"
    elif [[ $1 = "9" ]]; then
        echo "*.*"
    elif [[ $1 = "10" ]]; then
        echo "0.0"
    elif [[ $1 = "11" ]]; then
        echo "0 0"
    elif [[ $1 = "12" ]]; then
        echo "o o"
    elif [[ $1 = "13" ]]; then
        echo "o.o"
    else
        echo "^.^"
    fi
}

# sysinfo with cute kitty
kittyfetch() {
    printf '\n             %s%s%b  %s%s\n   /\_/\     %s%b  %s%s\n  ( %s%s%s )    %s%b  %s%s\n   %s>%s %s^%s %s<%s     %s%b  %s%s\n             %s%b  %s%s\n\n' \
        "$d" "$c1" '\xEF\x82\x8A' "$t" "$wmname" \
        "$c3" '\xEF\x82\xAD' "$t" "$kernel" \
        "$d" "$(eyes $1)" "$t" "$c2" '\xEF\x84\xA0' "$t" "$shell" \
        "$c1" "$t" "$c3" "$t" "$c1" "$t" "$c5" '\xEF\x80\xBE' "$t" "$resolution" \
        "$c4" '\xEF\x87\xAB' "$t" "$netname"
}

# sysinfo with cute bunny
bunnyfetch() {
    printf '\n             %s%s%b  %s%s\n   (\ /)     %s%b  %s%s\n   ( %s%s%s)    %s%b  %s%s\n   c(%s"%s)(%s"%s)   %s%b  %s%s\n             %s%b  %s%s\n\n' \
        "$d" "$c1" '\xEF\x82\x8A' "$t" "$wmname" \
        "$c3" '\xEF\x82\xAD' "$t" "$kernel" \
        "$d" "$(eyes $1)" "$t" "$c2" '\xEF\x84\xA0' "$t" "$shell" \
        "$c1" "$t" "$c1" "$t" "$c5" '\xEF\x80\xBE' "$t" "$resolution" \
        "$c4" '\xEF\x87\xAB' "$t" "$netname"
}

# script information
scriptinfo() {
    printf "cutefetch - simple colored script to display system info\n\
        Usage: cutefetch kitty/bunny\nIf no argument is given, kitty is assumed.\n\
        If unknown argument is given, this message is shown."
}

# print the fetch info, kitty by default, bunny otherwise
cutefunc() {
    tput clear
    setup_colors
    setup_variables
    if [[ -z $1 ]] || [[ $1 = "kitty" ]] || [[ $1 = "k" ]]; then
        kittyfetch $2
    elif [[ $1 = "bunny" ]] || [[ $1 = "b" ]]; then
        [[ -z $2 ]] && eye="0" || eye=$2
        bunnyfetch $eye
    elif [[ $1 = "?" ]]; then
        scriptinfo
    else
        kittyfetch $1
    fi
}

# call the main function
cutefunc $1 $2
