#!/usr/bin/env bash
# ----------------------------------------------------------------
# Cutefetch Mac v1.0
#
# Tiny colored fetch script with cute little animals
#
# Authored by: elenapan (https://github.com/elenapan)
# Modified by: strafe (https://github.com/strafe)
# Modified by: cybardev (https://github.com/cybardev)
# ----------------------------------------------------------------

# store color codes in variables
function setup_colors() {
    for i in {0..7}; do
        printf -v "c${i}" '%b' "\e[3${i}m"
    done

    readonly d=$'\e[1m'
    readonly t=$'\e[0m'
    readonly v=$'\e[7m'
}

# name of window manager
function get_wm() {
    # From neofetch (https://github.com/dylanaraps/neofetch).
    local -r ps_line="$(ps -e | grep -o \
    -e "[S]pectacle" \
    -e "[A]methyst" \
    -e "[k]wm" \
    -e "[c]hun[k]wm" \
    -e "[y]abai" \
    -e "[R]ectangle")"

    case $ps_line in
        *chunkwm*)   echo chunkwm ;;
        *kwm*)       echo Kwm ;;
        *yabai*)     echo yabai ;;
        *Amethyst*)  echo Amethyst ;;
        *Spectacle*) echo Spectacle ;;
        *Rectangle*) echo Rectangle ;;
        *)           echo Quartz ;;
    esac
}

function get_res() {
    # print resolution of multiple displays, separated by commas
    # echo "$(system_profiler SPDisplaysDataType | awk '/Resolution:/ {printf $2"x"$4"\n"}' | xargs | sed 's/ /, /g')"

    # print resolution of retina display
    echo "$(system_profiler SPDisplaysDataType | grep Retina | awk '/Resolution:/ {printf $2"x"$4"\n"}')"
}

# set necessary variables
function setup_variables() {
    # symbols
    readonly w="\xEF\x82\x8A"
    readonly k="\xEF\x82\xAD"
    readonly s="\xEF\x84\xA0"
    readonly r="\xEF\x80\xBE"
    readonly n="\xEF\x87\xAB"
    
    # info
    readonly wm="$(get_wm)"
    readonly kern="$(uname -r | cut -d '-' -f1)"
    readonly shell="$(basename "$SHELL")"
    readonly res="$(get_res)"
    readonly net="$(/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I  | awk -F' SSID: '  '/ SSID: / {print $2}')"
}

# set the eyes, ^.^ by default
eyes() {
    case "$1" in
        "0")  echo ". ." ;;
        "1")  echo "· ·" ;;
        "2")  echo "^ ^" ;;
        "3")  echo "- -" ;;
        "4")  echo "~ ~" ;;
        "5")  echo "* *" ;;
        "6")  echo "^.^" ;;
        "7")  echo "-.-" ;;
        "8")  echo "~.~" ;;
        "9")  echo "*.*" ;;
        "10") echo "0.0" ;;
        "11") echo "0 0" ;;
        "12") echo "o o" ;;
        "13") echo "o.o" ;;
        "*")  echo "^.^" ;;
    esac
}

# sysinfo with cute kitty
kittyfetch() {
    printf '\n             %s%s%b  %s%s\n   /\_/\     %s%b  %s%s\n  ( %s%s%s )    %s%b  %s%s\n   %s>%s %s^%s %s<%s     %s%b  %s%s\n             %s%b  %s%s\n\n' \
        "$d" "$c1" "$w" "$t" "$wm" \
        "$c3" "$k" "$t" "$kern" \
        "$d" "$(eyes $1)" "$t" "$c2" "$s" "$t" "$shell" \
        "$c1" "$t" "$c3" "$t" "$c1" "$t" "$c5" "$r" "$t" "$res" \
        "$c4" "$n" "$t" "$net"
}

# sysinfo with cute bunny
bunnyfetch() {
    printf '\n             %s%s%b  %s%s\n   (\ /)     %s%b  %s%s\n   ( %s%s%s)    %s%b  %s%s\n   c(%s"%s)(%s"%s)   %s%b  %s%s\n             %s%b  %s%s\n\n' \
        "$d" "$c1" "$w" "$t" "$wm" \
        "$c3" "$k" "$t" "$kern" \
        "$d" "$(eyes $1)" "$t" "$c2" "$s" "$t" "$shell" \
        "$c1" "$t" "$c1" "$t" "$c5" "$r" "$t" "$res" \
        "$c4" "$n" "$t" "$net"
}

# script information
scriptinfo() {
    printf "cutefetch - simple colored script to display system info\n"
    printf "Usage: cutefetch kitty/bunny\nIf no argument is given, kitty is assumed.\n"
    printf "       If unknown argument is given, this message is shown.\n"
}

# print the fetch info, kitty by default, bunny otherwise
cutefunc() {
    tput clear
    setup_colors
    setup_variables
    if [[ -z $1 ]] || [[ $1 = "kitty" ]] || [[ $1 = "k" ]]; then
        kittyfetch $2
    elif [[ $1 = "bunny" ]] || [[ $1 = "b" ]]; then
        [[ -z $2 ]] && eye="0" || eye=$2
        bunnyfetch $eye
    elif [[ $1 = "?" ]]; then
        scriptinfo
    else
        kittyfetch $1
    fi
}

# call the main function
cutefunc $1 $2
